server:
    port: 8888
    servlet:
    # 项目访问前缀
        context-path: /
        
#指定driver的类名，默认从jdbc url中自动探测. 
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/shiro?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    exceptionSorter: true
    filters: stat,wall,log4j
    initialSize: 5
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    poolPreparedStatements: false
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000.0
    type: com.alibaba.druid.pool.DruidDataSource
    useGlobalDataSourceStat: true
    validationQuery: SELECT 1 FROM DUAL
  servlet:
    multipart:
      maxFileSize: 300Mb
      maxRequestSize: 500Mb
      
mybatis:
  mapper-locations: classpath*:mapping/*Mapper.xml
    