server:
    port: 8080
    servlet:
    # 项目访问前缀
        context-path: /
#==================================
# datasource
#----------------------------------
spring:
    datasource:
        #指定driver的类名，默认从jdbc url中自动探测.
        driver-class-name: com.mysql.jdbc.Driver
        #数据库地址
        url: jdbc:mysql://www.junengxiong.cn/springboot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        #数据库秘钥       
        username: root
        password: rootroot
        #使用连接池类型
        type: com.alibaba.druid.pool.DruidDataSource
        #数据库连接池配置
        #指定启动连接池时，初始建立的连接数量
        initialSize: 5
        #指定必须保持连接的最小值(For DBCP and Tomcat connection pools)
        minIdle: 5
        #指定连接池中最大的活跃连接数.
        maxActive: 20
        #指定连接池等待连接返回的最大等待时间，毫秒单位.
        maxWait: 60000
        #指定空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔
        timeBetweenEvictionRunsMillis: 60000
        #指定一个空闲连接最少空闲多久后可被清除.
        minEvictableIdleTimeMillis: 300000
        #指定获取连接时连接校验的sql查询语句.
        validationQuery: SELECT 1 FROM DUAL
       #当连接空闲时，是否执行连接测试.
        testWhileIdle: false
        #在连接归还到连接池时是否测试该连接.
        testOnReturn: false
        #当数据库抛出一些不可恢复的异常时，抛弃连接
        exceptionSorter: true
        #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
        poolPreparedStatements: true
        #指定每个连接上PSCache的大小
        maxPoolPreparedStatementPerConnectionSize: 20
        #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有： 监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        useGlobalDataSourceStat: true
        
#==================================
# mybatis
#----------------------------------
#xml文件存放位置
mybatis:
    mapper-locations: classpath*:mapping/*Mapper.xml
#指定实体类包名
    type-aliases-package: cn.junengxiong.bean
        
        